### ISSUE TITLE
API related issues.

### ISSUE THREAD

**Issue by Savag3life** [brcdev-minecraft/shopgui-api#1]
Hello, 

There is no formatting for issues on this repo so I'm just going to make a list. All these issues are in relation to the API as it is in extremely rough shape right now.

- Events only contain ShopItems which you can get no info from. We either need ShopItem -> Itemstack support or direct Itemstack support in the event.

`
Material mat = ShopItem.getMaterialType();
`

- ShopGuiPlusApi.getPlugin().getConfigLang(), #getConfigShops, #getConfigMain return null
- There is no methods for supporting ShopName -> Shop & Its Items (IE material names etc.)

I've also noticed an issue with the plugin its self. If you limit the stack amount for an item, IE a chestplate, to 1 you still show the `Buy More` button. Not only that, they buy more tries to buy stacks of the limited stack size item (IE 64, 128, etc chestplates). Same for portions and such. If you don't limit these items, you will be given to players in stacks of 64, but if you limit them, players can only by 1 at a time as its limit to 1 per stack but buy more tries to give a 64 for 1 stack.

**Comment by Drc-DEV** [comment]
It's really sad how this is still relevant. Still can't get the itemstack from ShopItem in this API, while the actual jar has a getItem() method.

**Comment by brcdev** [comment]
@Savag3life @Drc-DEV 
These issues will be resolved as soon as possible, most likely by the end of the next week. My apologies for the inconvenience.

**Comment by brcdev** [comment]
> Events only contain ShopItems which you can get no info from. We either need ShopItem -> Itemstack support or direct Itemstack support in the event.
Many more methods were added in commits above to `ShopItem` and `Shop` classes.

> ShopGuiPlusApi.getPlugin().getConfigLang(), #getConfigShops, #getConfigMain return null
This should be fixed with commit resolving other issue (#2).

> There is no methods for supporting ShopName -> Shop & Its Items (IE material names etc.)
There already was the `ShopManager#getShopById` method, more were added anyway.

The issue with oversized "Buy more" stacks was resolved in ShopGUI+ 1.29.1. Option to disable "Buy more" for particular items will be added soon.
