### ISSUE TITLE
Null Pointer with method registerEconomyProvider

### ISSUE THREAD

**Issue by TheCoolestPaul** [brcdev-minecraft/shopgui-api#11]
With my Tokens plugin I have implemented your API to ShopGUI+, I will paste my code and the error below.

[My EconomyProvider](https://pastebin.com/Bhkpr2D0)
[The error in console](https://pastebin.com/VX0vxM6p)

**Comment by brcdev** [comment]
When exactly is the `TokenShopGUIPlus` constructor (in particular the `ShopGuiPlusApi.registerEconomyProvider(this);` line) called in your plugin?

**Comment by TheCoolestPaul** [comment]
It is ran inside of the `onEnable` method of my Tokens plugin.

**Comment by TheCoolestPaul** [comment]
Via this code
`if(Bukkit.getPluginManager().getPlugin("ShopGUIPlus")!=null){
			tokenShopGUIPlus = new TokenShopGUIPlus(this);
			this.getLogger().info("Successfully registered Tokens as ShopGUI+ economy");
		}`

**Comment by brcdev** [comment]
What versions of Tokens and ShopGUI+ were you trying it with? I've grabbed [this](https://github.com/TheCoolestPaul/Tokens/releases/tag/v3.9.7) build of Token and ShopGUI+ 1.42.0 and it it seems to be working perfectly fine:
```
[14:37:18] [Server thread/INFO]: [ShopGUIPlus] Registered custom economy provider 'Tokens'.
[14:37:18] [Server thread/INFO]: [Tokens] Successfully registered Tokens as ShopGUI+ economy
```

**Comment by TheCoolestPaul** [comment]
As in the error message dump it says `ShopGUIPlus (1.41.0), Tokens (3.9.7)` Might that be the error?

**Comment by brcdev** [comment]
It's rather unlikely but worth trying anyway.

**Comment by brcdev** [comment]
@TheCoolestPaul did updating resolve your issue?

**Comment by TheCoolestPaul** [comment]
I'm kind of the middle man on this issue. I am the Dev of Tokens and I used your API (Hopefully correctly) and a user of Tokens had this error and I was passing it on in an attempt to help them.. I assume it's fixed because they haven't responded. Thank you for the support!
