### ISSUE TITLE
Custom ItemProvider constructor accessibility problem

### ISSUE THREAD

**Issue by WouterGritter** [brcdev-minecraft/shopgui-api#14]
I'm currently tring to register a custom ItemProvider for a hook into ShopGUI+. I thought it was an intended feature of the API, but the constructor of the abstract class ItemProvider is non-accessible from packages other than itself.

Is this intended? If so, consider this as a bug. If not, it would be nice to have this as a feature.

**Comment by brcdev** [comment]
The ItemProvider wasn't supposed to be used via the API yet. Will add it as soon as possible.

**Comment by WouterGritter** [comment]
Do you have an ETA for my client?

**Comment by brcdev** [comment]
Fixed in release 2.1.1
