### ISSUE TITLE
getItemStackPriceSell is returning Buying price

### ISSUE THREAD

**Issue by Nekomitsuki** [brcdev-minecraft/shopgui-api#16]
When using plugin DeluxeSellWands, i noticed that ShopGuiPlus Hook was using Buying price instead of Selling price. I contacted author and there was nothing wrong with his code.

ShopGuiPlus version: 1.46.0

Plugin is using: `ShopGuiPlusApi.getItemStackPriceSell(player, itemStack);`

Screenshots:
https://imgur.com/a/0IYj3kV

**Comment by brcdev** [comment]
1. What ShopGUI+ version are you running? 
2. Are you able to tell (or already asked the DeluxeSellWands author) what ShopGUI+ API version they are using?

**Comment by brcdev** [comment]
I've contacted the DeluxeSellWands author and they confirmed it was an issue on your end and was already resolved.
