### ISSUE TITLE
Creating new special items doesnt work

### ISSUE THREAD

**Issue by JHarris12345** [brcdev-minecraft/shopgui-api#17]
Very simply, I have created a new special item called elfarmors:

![image](https://user-images.githubusercontent.com/46936647/99188019-c708a980-2751-11eb-9da9-dc9eb1748bbe.png)

And set it up as an item in the shop:

![image](https://user-images.githubusercontent.com/46936647/99188027-ce2fb780-2751-11eb-8c53-9f0ff70e5a82.png)

And it doesnt show up

**Comment by brcdev** [comment]
This repository and issues are dedicated for API-related issues only. Please use our Discord and other means of communication for reporting bugs with the plugin itself.
