### ISSUE TITLE
Player Statistic with Placeholders

### ISSUE THREAD

**Issue by Flearl** [brcdev-minecraft/shopgui-api#19]
I want to insert player statistics with placeholder, but this doesn't work
The plugin does not accept my placeholders
I use papi for my placeholders

11:
    type: dummy
    item:
      material: SUNFLOWER
      quantity: 1
      name: "&3%player% Statistik"
    slot: 39
    lore:
      - "&7%statistic_time_played%"

**Comment by brcdev** [comment]
This repository is dedicated for API related stuff only. Please use our discord server for plugin support (http://discord.brcdev.net/).
