### ISSUE TITLE
Bug with /sell handall

### ISSUE THREAD

**Issue by BaxAndrei** [brcdev-minecraft/shopgui-api#20]
I apologize for posting here, I hope you understand me. I haven't found where to post a bug for ShopGui+.

The problem is the following and is related to the command /sell handall

If I add an item in shop with quantity of 32, a strange bug will occur with that command.

For example, because quantity is set to 32, if one of my players try to use /sell handall and he has only 30 items (for that type of item) in his inventory, command will do nothing (also no message will be shown).

If he have a perfect multiple of 2 for example 32,64,128 etc, all will work as intended but if item count is not an multiple of 2, for example 33 or 97, he will get money only for 32 or 96 items and also all 33 or 97 items will be gone.

I attached a video:
https://youtu.be/49-91-HsgrQ

**Comment by brcdev** [comment]
It's most likely caused by some kind of misconfiguration on your end. However, we won't provide any further support here since it's a repository for API related issues only. For support, please use our discord server (http://discord.brcdev.net/).

**Comment by BaxAndrei** [comment]
Ty. I found issue and switched `allowAllSellAllStackSizes: true` and now all works great. But it would have been good if when he sells and the option is not activated, to take strictly the items that are multiple, not all.
