### ISSUE TITLE
getItemStackShopItem returns null if the item only has buy price and no sell price

### ISSUE THREAD

**Issue by MedicOP** [brcdev-minecraft/shopgui-api#21]
ShopGuiPlusApi.getItemStackShopItem returns null if the item only has a buy price defined and no sell price

**Comment by brcdev** [comment]
This behavior couldn't be reproduced with latest (1.78.0) ShopGUI+. I tried following scenarios:
* sell price above 0
* sell price equal to 0
* no sell price defined (defaults to -1)
and it always returned a non-null ShopItem object.
