### ISSUE TITLE
Shop Sell NBT bug

### ISSUE THREAD

**Issue by SirCraftypants** [brcdev-minecraft/shopgui-api#23]
Hi, 

Shopgui+ seems to fail to recognize individual custom items using the same material host.

Example: 

Hamburger using material COOKED_CHICKEN to host it's Custom Model Data
Cheeseburger using the same material host.

Buy 1 Hamburger and 2 Cheeseburgers

Sell back the Hamburger but increase the sale amount to 2.

It will sell the Hamburger and also 1 Cheeseburger.

I use Itemsadder to host my Custom Items.

Here is the Shop [Config](https://paste.helpch.at/vihatagehe.bash)

Paper 1.16.5

**Comment by brcdev** [comment]
This repository and issues are dedicated for API-related issues only. Please use our Discord and other means of communication for reporting bugs with the plugin itself.
