### ISSUE TITLE
dependencies are not working

### ISSUE THREAD

**Issue by e7a-0-e7a** [brcdev-minecraft/shopgui-api#25]
Hey, the Maven dependencies are not working.

I entered this with the repository's given here and it tells me that it is not found.

![Bildschirmfoto vom 2021-11-01 16-51-26](https://user-images.githubusercontent.com/87435355/139700960-645f8162-98e6-40d7-997a-7db003beff2c.png)

![Bildschirmfoto vom 2021-11-01 16-54-34](https://user-images.githubusercontent.com/87435355/139701195-07d72b20-f846-4b60-9640-076df98c0334.png)

**Comment by brcdev** [comment]
Hi,
Have you added the jitpack repository to the `repositories` section of your pom.xml?

**Comment by e7a-0-e7a** [comment]
yes

**Comment by brcdev** [comment]
It's now fixed, please make sure to update your dependencies according to the latest readme.
