### ISSUE TITLE
Softdepend mode not working

### ISSUE THREAD

**Issue by gmax79** [brcdev-minecraft/shopgui-api#27]
Case:
1. plugin.yml
   softdepend: [ ShopGUIPlus ]

2. shopgui-api.jar extracted into plugin.jar to resolve dependencies.

3. ShopGuiPlusApi.getPlugin() - returns null  at any case

**Comment by brcdev** [comment]
It's now fixed in 2.4.0. Please make sure to update your plugin according to the latest readme.
