### ISSUE TITLE
Method does not exist

### ISSUE THREAD

**Issue by Angeschossen** [brcdev-minecraft/shopgui-api#30]
Apparently, this method does not exist in the actual plugin:
https://github.com/brcdev-minecraft/shopgui-api/blob/eb41a5347039ace25bd3b00c6007b0c9d96d1004/src/main/java/net/brcdev/shopgui/event/ShopPreTransactionEvent.java#L30

I'm using the latest version of the API.
Anything I'm missing?

**Comment by brcdev** [comment]
This method exists and the signature is correct.

I assume the stack trace I received from one of SG+ users is related:
`java.lang.NoSuchMethodError: 'net.brcdev.shopgui.shop.ShopItem net.brcdev.shopgui.event.ShopPreTransactionEvent.getShopItem()'`
As you can see, it's the old method signature with ShopItem class being in the old package which was moved to item subpackage in version 3.0.0 of the API/1.78.0 of the plugin. I'm pretty sure the error will go away after they update the plugin to the latest version.
