### ISSUE TITLE
PerItemPermission Icon & Name Display

### ISSUE THREAD

**Issue by NotStarRift** [brcdev-minecraft/shopgui-api#4]
Hello,
I have a new feature suggestion or request for ShopGUIPlus.
It would be a really clean solution to have configurable interchangeable shop titles and icons dependent on if a user has permission or not. 

For example: 
Has permission = 
name: Diamond 
block: diamond_ore

Doesn't have permission =
name: [LOCKED]
block: BARRIER_BLOCK

**Comment by brcdev** [comment]
This isn't an API-related issue (which this repo is dedicated for), for feature requests please use our Discord: https://discord.brcdev.net/
