### ISSUE TITLE
CUSTOM currency prefix / suffix dont work

### ISSUE THREAD

**Issue by JHarris12345** [brcdev-minecraft/shopgui-api#7]
Ive correctly set prefixes and suffixes in config.yml and they work. However the custom ones dont work. They dont get used and the shop messages return just the number with no prefix / suffix

**Comment by brcdev** [comment]
It's already being investigated.
For now, please set the prefix and suffict directly in your EconomyProvider implementation [like this](https://github.com/brcdev-minecraft/shopgui-api-example-economy-provider/blob/master/src/main/java/net/brcdev/myeconomy/provider/MyEconomyProvider.java#L17).

**Comment by JHarris12345** [comment]
Hi sorry Im not a dev. How do I do that and does that involve me editing the shopgui jar or another jar to fix this?

**Comment by JHarris12345** [comment]
Dont worry I figured it out thanks!

**Comment by brcdev** [comment]
It was fixed in ShopGUI+ 1.55.0.
